[project]
name = "apsar-works"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "bcrypt>=4.3.0",
    "fastapi>=0.115.11",
    "loguru>=0.7.3",
    "sqlalchemy>=2.0.39",
    "uvicorn>=0.34.0",
]
